Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import yfinance as yf
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import mplfinance as mpf

vst = yf.Ticker("VST.CN")
data = vst.history(interval="1d", start="2020-08-08", end="2020-09-10")
mpf.plot(
    data,
    type="candle",
    mav=4,
    title="Victory Square Purchases Dates",
    vlines=dict(
        vlines=["2020-08-26", "2020-09-03", "2020-09-08"], linewidths=(0.5, 0.5, 0.5)
    ),
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3192[0m, in [0;36mDatabase.connect[0;34m(self, reuse_if_open)[0m
[1;32m   3191[0m [38;5;28;01mwith[39;00m __exception_wrapper__:
[0;32m-> 3192[0m     [38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mset_connection([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connect[49m[43m([49m[43m)[49m)
[1;32m   3193[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mserver_version [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3536[0m, in [0;36mSqliteDatabase._connect[0;34m(self)[0m
[1;32m   3535[0m     [38;5;28;01mraise[39;00m ImproperlyConfigured([38;5;124m'[39m[38;5;124mSQLite driver not installed![39m[38;5;124m'[39m)
[0;32m-> 3536[0m conn [38;5;241m=[39m [43msqlite3[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdatabase[49m[43m,[49m[43m [49m[43mtimeout[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_timeout[49m[43m,[49m
[1;32m   3537[0m [43m                       [49m[43misolation_level[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect_params[49m[43m)[49m
[1;32m   3538[0m [38;5;28;01mtry[39;00m:

[0;31mOperationalError[0m: unable to open database file

During handling of the above exception, another exception occurred:

[0;31mOperationalError[0m                          Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmplfinance[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpf[39;00m
[1;32m      6[0m vst [38;5;241m=[39m yf[38;5;241m.[39mTicker([38;5;124m"[39m[38;5;124mVST.CN[39m[38;5;124m"[39m)
[0;32m----> 7[0m data [38;5;241m=[39m [43mvst[49m[38;5;241;43m.[39;49m[43mhistory[49m[43m([49m[43minterval[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m1d[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mstart[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m2020-08-08[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mend[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m2020-09-10[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      8[0m mpf[38;5;241m.[39mplot(
[1;32m      9[0m     data,
[1;32m     10[0m     [38;5;28mtype[39m[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcandle[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m     15[0m     ),
[1;32m     16[0m )

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/yfinance/utils.py:114[0m, in [0;36mlog_indent_decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    111[0m logger[38;5;241m.[39mdebug([38;5;124mf[39m[38;5;124m'[39m[38;5;124mEntering [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m()[39m[38;5;124m'[39m)
[1;32m    113[0m [38;5;28;01mwith[39;00m IndentationContext():
[0;32m--> 114[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    116[0m logger[38;5;241m.[39mdebug([38;5;124mf[39m[38;5;124m'[39m[38;5;124mExiting [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m()[39m[38;5;124m'[39m)
[1;32m    117[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/yfinance/base.py:148[0m, in [0;36mTickerBase.history[0;34m(self, period, interval, start, end, prepost, actions, auto_adjust, back_adjust, repair, keepna, proxy, rounding, timeout, debug, raise_errors)[0m
[1;32m    145[0m end_user [38;5;241m=[39m end
[1;32m    146[0m [38;5;28;01mif[39;00m start [38;5;129;01mor[39;00m period [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m period[38;5;241m.[39mlower() [38;5;241m==[39m [38;5;124m"[39m[38;5;124mmax[39m[38;5;124m"[39m:
[1;32m    147[0m     [38;5;66;03m# Check can get TZ. Fail => probably delisted[39;00m
[0;32m--> 148[0m     tz [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_ticker_tz[49m[43m([49m[43mproxy[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m
[1;32m    149[0m     [38;5;28;01mif[39;00m tz [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    150[0m         [38;5;66;03m# Every valid ticker has a timezone. Missing = problem[39;00m
[1;32m    151[0m         err_msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mNo timezone found, symbol may be delisted[39m[38;5;124m"[39m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/yfinance/base.py:1644[0m, in [0;36mTickerBase._get_ticker_tz[0;34m(self, proxy, timeout)[0m
[1;32m   1642[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_tz [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1643[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_tz
[0;32m-> 1644[0m cache [38;5;241m=[39m [43mutils[49m[38;5;241;43m.[39;49m[43mget_tz_cache[49m[43m([49m[43m)[49m
[1;32m   1645[0m tz [38;5;241m=[39m cache[38;5;241m.[39mlookup([38;5;28mself[39m[38;5;241m.[39mticker)
[1;32m   1647[0m [38;5;28;01mif[39;00m tz [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m utils[38;5;241m.[39mis_valid_timezone(tz):
[1;32m   1648[0m     [38;5;66;03m# Clear from cache and force re-fetch[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/yfinance/utils.py:985[0m, in [0;36mget_tz_cache[0;34m()[0m
[1;32m    983[0m [38;5;28;01mif[39;00m _tz_cache [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    984[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 985[0m         _tz_cache [38;5;241m=[39m [43m_TzCache[49m[43m([49m[43m)[49m
[1;32m    986[0m     [38;5;28;01mexcept[39;00m _TzCacheException [38;5;28;01mas[39;00m err:
[1;32m    987[0m         get_yf_logger()[38;5;241m.[39minfo([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFailed to create TzCache, reason: [39m[38;5;132;01m{[39;00merr[38;5;132;01m}[39;00m[38;5;124m. [39m[38;5;124m"[39m
[1;32m    988[0m                              [38;5;124m"[39m[38;5;124mTzCache will not be used. [39m[38;5;124m"[39m
[1;32m    989[0m                              [38;5;124m"[39m[38;5;124mTip: You can direct cache to use a different location with [39m[38;5;124m'[39m[38;5;124mset_tz_cache_location(mylocation)[39m[38;5;124m'[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/yfinance/utils.py:926[0m, in [0;36m_TzCache.__init__[0;34m(self)[0m
[1;32m    925[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m):
[0;32m--> 926[0m     [43mdb[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m    927[0m     db[38;5;241m.[39mcreate_tables([KV])
[1;32m    929[0m     old_cache_file_path [38;5;241m=[39m _os[38;5;241m.[39mpath[38;5;241m.[39mjoin(_cache_dir, [38;5;124m"[39m[38;5;124mtkr-tz.csv[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3191[0m, in [0;36mDatabase.connect[0;34m(self, reuse_if_open)[0m
[1;32m   3188[0m     [38;5;28;01mraise[39;00m OperationalError([38;5;124m'[39m[38;5;124mConnection already opened.[39m[38;5;124m'[39m)
[1;32m   3190[0m [38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mreset()
[0;32m-> 3191[0m [38;5;28;01mwith[39;00m __exception_wrapper__:
[1;32m   3192[0m     [38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mset_connection([38;5;28mself[39m[38;5;241m.[39m_connect())
[1;32m   3193[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mserver_version [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3019[0m, in [0;36mExceptionWrapper.__exit__[0;34m(self, exc_type, exc_value, traceback)[0m
[1;32m   3017[0m new_type [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mexceptions[exc_type[38;5;241m.[39m[38;5;18m__name__[39m]
[1;32m   3018[0m exc_args [38;5;241m=[39m exc_value[38;5;241m.[39margs
[0;32m-> 3019[0m [43mreraise[49m[43m([49m[43mnew_type[49m[43m,[49m[43m [49m[43mnew_type[49m[43m([49m[43mexc_value[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43mexc_args[49m[43m)[49m[43m,[49m[43m [49m[43mtraceback[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:192[0m, in [0;36mreraise[0;34m(tp, value, tb)[0m
[1;32m    190[0m [38;5;28;01mdef[39;00m [38;5;21mreraise[39m(tp, value, tb[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    191[0m     [38;5;28;01mif[39;00m value[38;5;241m.[39m__traceback__ [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m tb:
[0;32m--> 192[0m         [38;5;28;01mraise[39;00m value[38;5;241m.[39mwith_traceback(tb)
[1;32m    193[0m     [38;5;28;01mraise[39;00m value

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3192[0m, in [0;36mDatabase.connect[0;34m(self, reuse_if_open)[0m
[1;32m   3190[0m [38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mreset()
[1;32m   3191[0m [38;5;28;01mwith[39;00m __exception_wrapper__:
[0;32m-> 3192[0m     [38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mset_connection([38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connect[49m[43m([49m[43m)[49m)
[1;32m   3193[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mserver_version [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3194[0m         [38;5;28mself[39m[38;5;241m.[39m_set_server_version([38;5;28mself[39m[38;5;241m.[39m_state[38;5;241m.[39mconn)

File [0;32m/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/peewee.py:3536[0m, in [0;36mSqliteDatabase._connect[0;34m(self)[0m
[1;32m   3534[0m [38;5;28;01mif[39;00m sqlite3 [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   3535[0m     [38;5;28;01mraise[39;00m ImproperlyConfigured([38;5;124m'[39m[38;5;124mSQLite driver not installed![39m[38;5;124m'[39m)
[0;32m-> 3536[0m conn [38;5;241m=[39m [43msqlite3[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdatabase[49m[43m,[49m[43m [49m[43mtimeout[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_timeout[49m[43m,[49m
[1;32m   3537[0m [43m                       [49m[43misolation_level[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect_params[49m[43m)[49m
[1;32m   3538[0m [38;5;28;01mtry[39;00m:
[1;32m   3539[0m     [38;5;28mself[39m[38;5;241m.[39m_add_conn_hooks(conn)

[0;31mOperationalError[0m: unable to open database file
OperationalError: unable to open database file

